// This file would be generated by GraphQL Code Generator
// For demo purposes, I'm providing the types manually

export interface Post {
  id: string
  title: string
  slug: string
  excerpt: string
  content?: string
  publishedAt: string | null
  category: string
  tags: string
  coverImage: { url: string }[]
}

export interface GetAllPostsQuery {
  posts: Post[]
}

export interface GetPostBySlugQuery {
  post: Post | null
}

// GraphQL Documents (normally generated)
export const GetAllPostsDocument = `
  query GetAllPosts {
    posts(orderBy: publishedAt_DESC) {
      id
      title
      slug
      excerpt
      publishedAt
      category
      tags
      coverImage {
        url
      }
    }
  }
`

export const GetPostBySlugDocument = `
  query GetPostBySlug($slug: String!) {
    posts(where: { slug: $slug }) {
      id
      title
      slug
      excerpt
      content
      publishedAt
      category
      tags
      coverImage {
        url
      }
    }
  }
`
